from django.conf.urls.defaults import *

urlpatterns = patterns('workflow.core.views',

     (r'^logout/$', 'logout_view'),
     (r'^$', 'main'),
     (r'^main/$', 'main'),
     (r'^item/$', 'item'),
     (r'^item/get/$', 'get_item'),
     (r'^item/(?P<item_id>.+)/file/new/$', 'item_file'),
     (r'^item/(?P<item_id>.+)/file/(?P<file_name>.+)/$', 'item_file'),
     (r'^item/(?P<item_id>.+)/problem/new/$', 'problem_new'),
     (r'^item/(?P<item_id>.+)/$', 'item_detail'),
     (r'^problem/(?P<problem_id>.+)/$', 'problem_detail'),
     (r'^transaction/$', 'transaction'),
     (r'^reports/$', 'reports'),
     (r'^admin/$', 'admin'),
     (r'^sequence/$', 'sequence_list'),
     (r'^sequence/new/$', 'sequence_new'),
     (r'^sequence/(?P<sequence_id>.+)/$', 'sequence_detail'),
     (r'^batch/$', 'batch', {'view': 'active'}),
    # (r'^batch/all/$', 'batch', {'view': 'all'}),
     (r'^batch/new/$', 'batch_new'),
     (r'^batch/(?P<batch_name>.+)/change_status/$', 'batch_status_change'),
     (r'^batch/(?P<batch_id>.+)/change_active/$', 'batch_active_change'),
     (r'^batch/(?P<batch_name>.+)/add_items/$', 'batch_add_items'),
     (r'^batch/(?P<batch_name>.+)/add_item/$', 'batch_add_single_item'),
     (r'^batch/(?P<batch_name>.+)/(?P<new>.+)/$', 'batch_detail'),
     (r'^batch/(?P<batch_name>.+)/$', 'batch_detail'),
     (r'^collection/$', 'collection'),
     (r'^collection/(?P<collection_id>.+)/$', 'collection_detail'),
     (r'^property_owner/$', 'property_owner'),
     (r'^property_owner/(?P<property_owner_id>.+)/$', 'property_owner_detail'),
     (r'^item_type/$', 'item_type'),
     (r'^item_type/(?P<item_type_id>.+)/$', 'item_type_detail'),
     (r'^status/change/$', 'setup_status_change'),
     (r'^status/change/(?P<action>.+)/(?P<complete>.+)/$', 'status_change'),
     (r'^status/ready/(?P<action>.+)/$', 'status_ready'),
     (r'^transactions/$', 'transactions'),

)
