from django.conf.urls.defaults import *

urlpatterns = patterns('',

     (r'^logout/$', 'workflow.wflocal.views.logout_view'),
     (r'^$', 'workflow.wflocal.views.main'),
     (r'^main/$', 'workflow.wflocal.views.main'),
     (r'^item/$', 'workflow.wflocal.views.item'),
     (r'^item/get/$', 'workflow.wflocal.views.get_item'),
     (r'^item/(?P<item_id>.+)/file/new/$', 'workflow.wflocal.views.item_file'),
     (r'^item/(?P<item_id>.+)/file/(?P<file_name>.+)/$', 'workflow.wflocal.views.item_file'),
     (r'^item/(?P<item_id>.+)/problem/new/$', 'workflow.wflocal.views.problem_new'),
     (r'^item/(?P<item_id>.+)/json/$', 'workflow.wflocal.views.get_item_json'),
     (r'^item/(?P<item_id>.+)/$', 'workflow.wflocal.views.item_detail'),
     (r'^problem/(?P<problem_id>.+)/$', 'workflow.wflocal.views.problem_detail'),
     (r'^transaction/$', 'workflow.wflocal.views.transaction'),
     (r'^reports/$', 'workflow.wflocal.views.reports'),
     (r'^admin/$', 'workflow.wflocal.views.admin'),
     (r'^sequence/$', 'workflow.wflocal.views.sequence_list'),
     (r'^sequence/new/$', 'workflow.wflocal.views.sequence_new'),
     (r'^sequence/(?P<sequence_id>.+)/$', 'workflow.wflocal.views.sequence_detail'),
     (r'^batch/$', 'workflow.wflocal.views.batch'),
     (r'^batch/new/$', 'workflow.wflocal.views.batch_new'),
     (r'^batch/(?P<batch_name>.+)/change_status/$', 'workflow.wflocal.views.batch_status_change'),
     (r'^batch/(?P<batch_id>.+)/change_active/$', 'workflow.wflocal.views.batch_active_change'),
     (r'^batch/(?P<batch_name>.+)/add_items/$', 'workflow.wflocal.views.batch_add_items'),
     (r'^batch/(?P<batch_name>.+)/add_item/$', 'workflow.wflocal.views.batch_add_single_item'),
     (r'^batch/(?P<batch_name>.+)/(?P<new>.+)/$', 'workflow.wflocal.views.batch_detail'),
     (r'^batch/(?P<batch_name>.+)/$', 'workflow.wflocal.views.batch_detail'),
     (r'^collection/$', 'workflow.wflocal.views.collection'),
     (r'^collection/(?P<collection_id>.+)/$', 'workflow.wflocal.views.collection_detail'),
     (r'^property_owner/$', 'workflow.wflocal.views.property_owner'),
     (r'^property_owner/(?P<property_owner_id>.+)/$', 'workflow.wflocal.views.property_owner_detail'),
     (r'^item_type/$', 'workflow.wflocal.views.item_type'),
     (r'^item_type/(?P<item_type_id>.+)/$', 'workflow.wflocal.views.item_type_detail'),
     (r'^status/change/$', 'workflow.wflocal.views.setup_status_change'),
     (r'^status/change/(?P<action>.+)/(?P<complete>.+)/$', 'workflow.wflocal.views.status_change'),
     (r'^status/ready/(?P<action>.+)/$', 'workflow.wflocal.views.status_ready'),
     (r'^transactions/$', 'workflow.wflocal.views.transactions'),
    # -- old local stuff follows
     (r'^collection_building/$', 'workflow.wflocal.views.collection_building'),
     (r'^collection_building/(?P<collection_id>.+)/$', 'workflow.wflocal.views.collection_building_detail'),
     (r'^stats/$', 'workflow.wflocal.views.stats'),
     (r'^rebuilds$', 'workflow.wflocal.views.coll_rebuilds'),
     (r'^metadata_maps$', 'workflow.wflocal.views.metadata_maps'),
     (r'^report_online$', 'workflow.wflocal.views.register_online_collection_items'),
     (r'^moveProblemItem$', 'workflow.wflocal.views.item_to_problems'),
     (r'^refreshMetadataFiles$', 'workflow.wflocal.views.refresh_metadata_files'),
     (r'^get_online_items/$', 'workflow.wflocal.views.get_online_items'),
     (r'^local_item/(?P<item_id>.+)/$', 'workflow.wflocal.views.local_item'),

)
